In [10]:
import sys
import csv
import glob
import pandas as pd

# get data file names
path =r'E:\Dropbox (Personal)\CodingDropbox\Github\1 codingtemple-july2020\Capstone\Elections\files\GA_November8_2016(CountyPrecinct)'
filenames = glob.glob(path + "/*.xlsx")

dfs = []
for df in dfs: 
    xl_file = pd.ExcelFile(filenames)
    df=xl_file.parse('DEMOGRAPHICS REPORT')
    dfs.concat(df, ignore_index=True)
dfs

[]

In [3]:
import sys
import csv
import glob
import pandas as pd
from os import getcwd, listdir
from os.path import basename

dfs= []
path = r'.\files\GA_November8_2016(CountyPrecinct)'
files = listdir(path)
for i in files:
    dfs.append(path + "/" + i)
print(path, files)

df = []
for f in dfs:
    voter_cols = ['ID','Precinct','BM','BF','BU','WM','WF','WU','APacM','APacF','APacU','HM','HF','HU','NM','NF','NU','OM','OF','OU','UNKNOWN MALE','UNKNOWN FEMALE','UNKNOWN','TOTAL VOTERS']
    column_range = "A,B,C,F,I,L,O,R,U,X,AA,AD,AG,AJ,AM, AP,AS, AV, AY, BB, BE,BH, BK,BN"
    data = pd.read_excel(f, 'DEMOGRAPHICS REPORT', header=None, names=voter_cols, index_col=0,  usecols=column_range, skiprows=3)
    data.index = [basename(f)] * len(data)
    df.append(data)

df = pd.concat(df)
df

.\files\GA_November8_2016(CountyPrecinct) ['APPLING.xlsx', 'ATKINSON.xlsx', 'BACON.xlsx', 'BAKER.xlsx', 'BALDWIN.xlsx', 'BANKS.xlsx', 'BARROW.xlsx', 'BARTOW.xlsx', 'BEN HILL.xlsx', 'BERRIEN.xlsx', 'BIBB.xlsx', 'BLECKLEY.xlsx', 'BRANTLEY.xlsx', 'BROOKS.xlsx', 'BRYAN.xlsx', 'BULLOCH.xlsx', 'BURKE.xlsx', 'BUTTS.xlsx', 'CALHOUN.xlsx', 'CAMDEN.xlsx', 'CANDLER.xlsx', 'CARROLL.xlsx', 'CATOOSA.xlsx', 'CHARLTON.xlsx', 'CHATHAM.xlsx', 'CHATTAHOOCHEE.xlsx', 'CHATTOOGA.xlsx', 'CHEROKEE.xlsx', 'CLARKE.xlsx', 'CLAY.xlsx', 'CLAYTON.xlsx', 'CLINCH.xlsx', 'COBB.xlsx', 'COFFEE.xlsx', 'COLQUITT.xlsx', 'COLUMBIA.xlsx', 'COOK.xlsx', 'COWETA.xlsx', 'CRAWFORD.xlsx', 'CRISP.xlsx', 'DADE.xlsx', 'DAWSON.xlsx', 'DECATUR.xlsx', 'DEKALB.xlsx', 'DODGE.xlsx', 'DOOLY.xlsx', 'DOUGHERTY.xlsx', 'DOUGLAS.xlsx', 'EARLY.xlsx', 'ECHOLS.xlsx', 'EFFINGHAM.xlsx', 'ELBERT.xlsx', 'EMANUEL.xlsx', 'EVANS.xlsx', 'FANNIN.xlsx', 'FAYETTE.xlsx', 'FLOYD.xlsx', 'FORSYTH.xlsx', 'FRANKLIN.xlsx', 'FULTON.xlsx', 'GILMER.xlsx', 'GLASCOCK.xlsx', 'GLYNN.xlsx', 'GORDON.xlsx', 'GRADY.xlsx', 'GREENE.xlsx', 'GWINNETT.xlsx', 'HABERSHAM.xlsx', 'HALL.xlsx', 'HANCOCK.xlsx', 'HARALSON.xlsx', 'HARRIS.xlsx', 'HART.xlsx', 'HEARD.xlsx', 'HENRY.xlsx', 'HOUSTON.xlsx', 'IRWIN.xlsx', 'JACKSON.xlsx', 'JASPER.xlsx', 'JEFF DAVIS.xlsx', 'JEFFERSON.xlsx', 'JENKINS.xlsx', 'JOHNSON.xlsx', 'JONES.xlsx', 'LAMAR.xlsx', 'LANIER.xlsx', 'LAURENS.xlsx', 'LEE.xlsx', 'LIBERTY.xlsx', 'LINCOLN.xlsx', 'LONG.xlsx', 'LOWNDES.xlsx', 'LUMPKIN.xlsx', 'MACON.xlsx', 'MADISON.xlsx', 'MARION.xlsx', 'MCDUFFIE.xlsx', 'MCINTOSH.xlsx', 'MERIWETHER.xlsx', 'MILLER.xlsx', 'MITCHELL.xlsx', 'MONROE.xlsx', 'MONTGOMERY.xlsx', 'MORGAN.xlsx', 'MURRAY.xlsx', 'MUSCOGEE.xlsx', 'NEWTON.xlsx', 'OCONEE.xlsx', 'OGLETHORPE.xlsx', 'PAULDING.xlsx', 'PEACH.xlsx', 'PICKENS.xlsx', 'PIERCE.xlsx', 'PIKE.xlsx', 'POLK.xlsx', 'PULASKI.xlsx', 'PUTNAM.xlsx', 'QUITMAN.xlsx', 'RABUN.xlsx', 'RANDOLPH.xlsx', 'RICHMOND.xlsx', 'ROCKDALE.xlsx', 'SCHLEY.xlsx', 'SCREVEN.xlsx', 'SEMINOLE.xlsx', 'SPALDING.xlsx', 'STEPHENS.xlsx', 'STEWART.xlsx', 'SUMTER.xlsx', 'TALBOT.xlsx', 'TALIAFERRO.xlsx', 'TATTNALL.xlsx', 'TAYLOR.xlsx', 'TELFAIR.xlsx', 'TERRELL.xlsx', 'THOMAS.xlsx', 'TIFT.xlsx', 'TOOMBS.xlsx', 'TOWNS.xlsx', 'TREUTLEN.xlsx', 'TROUP.xlsx', 'TURNER.xlsx', 'TWIGGS.xlsx', 'UNION.xlsx', 'UPSON.xlsx', 'WALKER.xlsx', 'WALTON.xlsx', 'WARE.xlsx', 'WARREN.xlsx', 'WASHINGTON.xlsx', 'WAYNE.xlsx', 'WEBSTER.xlsx', 'WHEELER.xlsx', 'WHITE.xlsx', 'WHITFIELD.xlsx', 'WILCOX.xlsx', 'WILKES.xlsx', 'WILKINSON.xlsx', 'WORTH.xlsx']

,Precinct,WM,WF,WU,BM,BF,BU,APacM,APacF,APacU,...,NM,NF,NU,OM,OF,OU,UNKNOWN MALE,UNKNOWN FEMALE,UNKNOWN,TOTAL VOTERS
APPLING.xlsx,1B,36,41,0,538,590,1,1,4,0,...,1,0,0,4,2,0,15,12,0,1258
APPLING.xlsx,1C,8,14,0,369,395,0,0,0,0,...,0,0,0,1,1,0,6,11,0,815
APPLING.xlsx,2,624,818,0,314,407,0,5,2,0,...,3,0,0,9,10,0,32,19,0,2290
APPLING.xlsx,3A,0,1,0,141,154,0,0,0,0,...,0,0,0,0,0,0,1,2,0,301
APPLING.xlsx,3A1,8,6,0,219,230,0,0,0,0,...,0,0,0,0,1,0,8,9,0,482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WORTH.xlsx,RED ROCK,79,108,0,407,426,0,0,2,0,...,1,0,0,4,2,0,20,14,0,1070
WORTH.xlsx,DOLES,15,18,0,175,176,0,0,4,0,...,0,0,0,0,2,0,8,7,0,408
WORTH.xlsx,OAKFIELD,32,36,0,74,68,0,0,2,0,...,0,0,0,0,2,0,4,1,0,219
WORTH.xlsx,88888,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
WORTH.xlsx,WARWICK,94,117,0,235,241,0,0,0,0,...,0,0,0,2,1,0,7,2,0,702

In [29]:
import sys
import csv
import glob
import pandas as pd
from os import getcwd, listdir
from os.path import basename
import sqlalchemy

dfs= []
path = r'.\files\GA_November8_2016(CountyPrecinct)'
files = listdir(path)
for i in files:
    dfs.append(path + "/" + i)
print(path, files)

df = []
totals = []
for f in dfs:
    data2 = []
    voter_cols = ['ID','Precinct','BM','BF','BU','WM','WF','WU','APacM','APacF','APacU','HM','HF','HU','NM','NF','NU','OM','OF','OU','UNKNOWN MALE','UNKNOWN FEMALE','UNKNOWN','TOTAL VOTERS']
    column_range = "A,B,C,F,I,L,O,R,U,X,AA,AD,AG,AJ,AM, AP,AS, AV, AY, BB, BE,BH, BK,BN"
    data = pd.read_excel(f, 'DEMOGRAPHICS REPORT', header=None, names=voter_cols, index_col=0,  usecols=column_range, skiprows=3)
    
    indexName = (basename(f[:-5])) + '-' + (data['Precinct'].astype(str))
    county = (basename(f[:-5]))
#     data.loc[f'{county}-Total'] = data.sum()
    data.index = indexName
    data = data.drop(['Precinct'], axis=1)
    
    
    data.loc[f'{county}-Total'] = data.sum()
    data2 = data.loc[f'{county}-Total']
    totals.append(data2)
    def population(df):
        df['POW_w_Un_Voters'] = df.drop(['WM','WF','WU','TOTAL VOTERS'], axis=1).sum(axis=1)
        df['POW_wo_Un_Voters'] = df.drop(['WM','WF','WU','UNKNOWN MALE','UNKNOWN FEMALE','UNKNOWN','TOTAL VOTERS','POW_w_Un_Voters'], axis=1).sum(axis=1)
        df['White_Voters'] = df['WM']+df['WF']+df['WU']
        df['POC %'] = round(((df['POW_wo_Un_Voters'] / df['TOTAL VOTERS']) * 100), 2)

    population(data)

    data.to_excel(f'./files/Stripped-Data/{county}_appended.xlsx')
    
#     totalName = f'{county}-Total'
#     totals.append(data.loc[f'{totalName}'], ignore_index=False)

    df.append(data)

df = pd.concat(df)
# totals = pd.concat(totals)

.\files\GA_November8_2016(CountyPrecinct) ['APPLING.xlsx', 'ATKINSON.xlsx', 'BACON.xlsx', 'BAKER.xlsx', 'BALDWIN.xlsx', 'BANKS.xlsx', 'BARROW.xlsx', 'BARTOW.xlsx', 'BEN HILL.xlsx', 'BERRIEN.xlsx', 'BIBB.xlsx', 'BLECKLEY.xlsx', 'BRANTLEY.xlsx', 'BROOKS.xlsx', 'BRYAN.xlsx', 'BULLOCH.xlsx', 'BURKE.xlsx', 'BUTTS.xlsx', 'CALHOUN.xlsx', 'CAMDEN.xlsx', 'CANDLER.xlsx', 'CARROLL.xlsx', 'CATOOSA.xlsx', 'CHARLTON.xlsx', 'CHATHAM.xlsx', 'CHATTAHOOCHEE.xlsx', 'CHATTOOGA.xlsx', 'CHEROKEE.xlsx', 'CLARKE.xlsx', 'CLAY.xlsx', 'CLAYTON.xlsx', 'CLINCH.xlsx', 'COBB.xlsx', 'COFFEE.xlsx', 'COLQUITT.xlsx', 'COLUMBIA.xlsx', 'COOK.xlsx', 'COWETA.xlsx', 'CRAWFORD.xlsx', 'CRISP.xlsx', 'DADE.xlsx', 'DAWSON.xlsx', 'DECATUR.xlsx', 'DEKALB.xlsx', 'DODGE.xlsx', 'DOOLY.xlsx', 'DOUGHERTY.xlsx', 'DOUGLAS.xlsx', 'EARLY.xlsx', 'ECHOLS.xlsx', 'EFFINGHAM.xlsx', 'ELBERT.xlsx', 'EMANUEL.xlsx', 'EVANS.xlsx', 'FANNIN.xlsx', 'FAYETTE.xlsx', 'FLOYD.xlsx', 'FORSYTH.xlsx', 'FRANKLIN.xlsx', 'FULTON.xlsx', 'GILMER.xlsx', 'GLASCOCK.xlsx', 'GLYNN.xlsx', 'GORDON.xlsx', 'GRADY.xlsx', 'GREENE.xlsx', 'GWINNETT.xlsx', 'HABERSHAM.xlsx', 'HALL.xlsx', 'HANCOCK.xlsx', 'HARALSON.xlsx', 'HARRIS.xlsx', 'HART.xlsx', 'HEARD.xlsx', 'HENRY.xlsx', 'HOUSTON.xlsx', 'IRWIN.xlsx', 'JACKSON.xlsx', 'JASPER.xlsx', 'JEFF DAVIS.xlsx', 'JEFFERSON.xlsx', 'JENKINS.xlsx', 'JOHNSON.xlsx', 'JONES.xlsx', 'LAMAR.xlsx', 'LANIER.xlsx', 'LAURENS.xlsx', 'LEE.xlsx', 'LIBERTY.xlsx', 'LINCOLN.xlsx', 'LONG.xlsx', 'LOWNDES.xlsx', 'LUMPKIN.xlsx', 'MACON.xlsx', 'MADISON.xlsx', 'MARION.xlsx', 'MCDUFFIE.xlsx', 'MCINTOSH.xlsx', 'MERIWETHER.xlsx', 'MILLER.xlsx', 'MITCHELL.xlsx', 'MONROE.xlsx', 'MONTGOMERY.xlsx', 'MORGAN.xlsx', 'MURRAY.xlsx', 'MUSCOGEE.xlsx', 'NEWTON.xlsx', 'OCONEE.xlsx', 'OGLETHORPE.xlsx', 'PAULDING.xlsx', 'PEACH.xlsx', 'PICKENS.xlsx', 'PIERCE.xlsx', 'PIKE.xlsx', 'POLK.xlsx', 'PULASKI.xlsx', 'PUTNAM.xlsx', 'QUITMAN.xlsx', 'RABUN.xlsx', 'RANDOLPH.xlsx', 'RICHMOND.xlsx', 'ROCKDALE.xlsx', 'SCHLEY.xlsx', 'SCREVEN.xlsx', 'SEMINOLE.xlsx', 'SPALDING.xlsx', 'STEPHENS.xlsx', 'STEWART.xlsx', 'SUMTER.xlsx', 'TALBOT.xlsx', 'TALIAFERRO.xlsx', 'TATTNALL.xlsx', 'TAYLOR.xlsx', 'TELFAIR.xlsx', 'TERRELL.xlsx', 'THOMAS.xlsx', 'TIFT.xlsx', 'TOOMBS.xlsx', 'TOWNS.xlsx', 'TREUTLEN.xlsx', 'TROUP.xlsx', 'TURNER.xlsx', 'TWIGGS.xlsx', 'UNION.xlsx', 'UPSON.xlsx', 'WALKER.xlsx', 'WALTON.xlsx', 'WARE.xlsx', 'WARREN.xlsx', 'WASHINGTON.xlsx', 'WAYNE.xlsx', 'WEBSTER.xlsx', 'WHEELER.xlsx', 'WHITE.xlsx', 'WHITFIELD.xlsx', 'WILCOX.xlsx', 'WILKES.xlsx', 'WILKINSON.xlsx', 'WORTH.xlsx']

In [28]:
print(totals)

BM                  954
BF                 1247
BU                    0
WM                 3955
WF                 4512
                  ...
OU                    0
UNKNOWN MALE        217
UNKNOWN FEMALE      163
UNKNOWN               4
TOTAL VOTERS      13111
Length: 3498, dtype: int64

In [19]:
df.to_excel(f'./files/Stripped-Data/ALL-Georgia.xlsx')
totals.to_excel(f'./files/Stripped-Data/ALL-Georgia_CountyTotals.xlsx')